### ISSUE TITLE
Uncaught TypeError: Cannot read property 'closeMessage' of undefined

### ISSUE THREAD

**Issue by simeonwillbanks** [Pallinder/rails-test-runner#7]
👋 I'm on Code `Version 1.33.0 (1.33.0)` and Rails Test Runner `0.0.4`, and the runner isn't working anymore.  This is my first `code` issue, so please ask for any info you need that I didn't provide!

![Screen Shot 2019-04-05 at 11 27 37 AM](https://user-images.githubusercontent.com/164506/55648739-f1347000-5795-11e9-86d5-eeee3b08aed7.png)

![Screen Shot 2019-04-05 at 11 28 40 AM](https://user-images.githubusercontent.com/164506/55648750-fb566e80-5795-11e9-9cff-18ce56010f67.png)

![Screen Shot 2019-04-05 at 11 25 11 AM](https://user-images.githubusercontent.com/164506/55648663-c4805880-5795-11e9-95bc-5f763f5e3199.png)

<img width="359" alt="Screen Shot 2019-04-05 at 11 25 47 AM" src="https://user-images.githubusercontent.com/164506/55648668-c6e2b280-5795-11e9-9fc9-9364fa6df817.png">

**Comment by simeonwillbanks** [comment]
I tried a different window, and the runner worked as expected.  I restarted `code`, and the window with the error now works.  Closing!

**Comment by simeonwillbanks** [comment]
So, this keeps happening, and it does go away if VS Code is restarted or the window is reloaded.

If anyone has any thoughts, let me know.  If this issue is unrelated to `rails-test-runner`, I'm happy to close this issue.  

Thanks!

**Comment by simeonwillbanks** [comment]
Hmm, maybe something with `vscode-xterm`?

```
ERR Cannot read property 'closeMessage' of undefined: TypeError: Cannot read property 'closeMessage' of undefined
    at Object.leaveCallback [as hoverLeaveCallback] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2949:1007)
    at MouseZone.leaveCallback (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Linkifier.js:194:25)
    at MouseZoneManager.clearAll (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/ui/MouseZoneManager.js:59:39)
    at Terminal.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/Terminal.js:428:105)
    at Terminal.EventEmitter.emit (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/common/EventEmitter.js:70:20)
    at Terminal.emit (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-xterm/lib/public/Terminal.js:47:20)
    at e.setVisible (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3732:559)
    at terminalInstances.forEach.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3566:638)
    at Array.forEach (<anonymous>)
    at g.setVisible (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3566:625)
    at _terminalTabs.forEach (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3749:165)
    at Array.forEach (<anonymous>)
    at Proxy.setActiveInstanceByIndex (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3749:148)
    at Proxy.setActiveInstance (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3748:364)
    at h.$show (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3244:828)
    at u._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3314:202)
    at u._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3313:894)
    at u._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3312:547)
    at u._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3311:283)
    at _protocol.onMessage.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3309:565)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:416)
    at a (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:317:553)
    at e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:317:599)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:416)
    at _receiveMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:326:276)
    at _socketDisposables.push._socketReader.onMessage.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:323:562)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:416)
    at g.acceptChunk (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:320:195)
    at _register._socket.onData.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:319:522)
    at Socket.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:328:483)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

**Comment by simeonwillbanks** [comment]
I'm pretty sure this isn't `rails-test-runner`.  I'll close.  Thanks for being my rubber duck!
